config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_for :views

  root 'places#index'

  resources  :places do
    resources :comments, only: :create
    resources :photos, only: :create
  end
  resources :users, only: :show

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :place
  after_create :send_comment_email

  RATINGS = {
    '*'          => '1_star',
    '* *'        => '2_star',
    '* * *'      => '3_star',
    '* * * *'    => '4_star',
    '* * * * *'  => '5_star',
  }

  def humanized_rating
    RATINGS.invert[self.rating]
  end

  def send_comment_email
    NotificationMailer.comment_added(self).deliver
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :place

  mount_uploader :picture, PictureUploader
end

app/models/place.rb
class Place < ActiveRecord::Base
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :photos, dependent: :destroy

    geocoded_by :address
    after_validation :geocode


    validates :name, presence: true,
                     length: { maximum: 60, minimum: 3 },
                     uniqueness: { case_sensitive: false, message: 'Place Name already taken. It must be unique.' }            
    validates :address, presence: true, length: { maximum: 140, minimum: 3 }
    validates :description, presence: true, length: { maximum: 500, minimum: 10}

    def last_comment
      self.comments.order("id ASC").last
    end

    def last_photo
      self.photos.order("id ASC").last
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :places
  has_many :comments
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
      @place = Place.find(params[:place_id])
      @place.comments.create(comment_params.merge(user: current_user))
      redirect_to place_path(@place)
  end

  private

  def comment_params
    params.require(:comment).permit(:message, :rating)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!
  def create
      @place = Place.find(params[:place_id])
      @place.photos.create(photo_params)
      redirect_to place_path(@place)
  end

  private

  def photo_params
    params.require(:photo).permit(:picture, :caption)
  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @places = Place.all.paginate(:page => params[:page], :per_page => 4).order('name ASC')
  end

  def new
    @place = Place.new
  end

  def create
    @place = current_user.places.create(place_params)
    if @place.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @place = Place.find(params[:id])
    @comment = Comment.new
    @photo = Photo.new
  end

  def edit
    @place = Place.find(params[:id])

    if @place.user != current_user
      render file: Rails.root.join('public','403_forbidden.html'), status: :not_found, layout: false
    end
  end

  def update
    @place = Place.find(params[:id])
    if @place.user != current_user
      return render text: 'You are not the owner of this place', status: :forbidden
    end

    @place.update_attributes(place_params)
    if @place.valid?
      redirect_to root_path
    else
      return render text: 'Update Forbidden', status: :unprocessable_entity
    end
  end

  def destroy
    @place = Place.find(params[:id])
    if @place.user != current_user
      return render text: 'Destroy Forbidden', status: :unprocessable_entity
    end
    @place.destroy
    redirect_to root_path
  end

  private

  def place_params
    params.required(:place).permit(:name, :address, :description)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper
  
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper

  
end

app/helpers/users_helper.rb
module UsersHelper
end   # helper

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dogster</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name='viewport' content='width=device-width, initial-scale=1'>
</head>

<body>
<!-- NAVBAR -->
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Dogster', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to new_place_path do %>
            <i class='glyphicon glyphicon-plus-sign'></i>
            New Place
          <% end %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'My Profile', user_path(current_user) %></li>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>   <!-- /.navbar-collapse -->
  </div>   <!-- /.container-fluid -->
</nav>

<div class='content-container'>
  <div class='container-fluid'>
    <!-- User Authentication -->
    <% if notice.present? %>
      <p class='alert alert-info'><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class='alert alert-danger'><%= alert %></p>
    <% end %>

    <%= yield %>
  </div>   <!-- div container wrapping the content -->
</div>   <!-- div content-container -->


<!-- http://stackoverflow.com/questions/17966140/twitter-bootstrap-3-sticky-footer -->
<footer>
<div class='container'>
  <div class='col-xs-1'>
    <span class='dog-paw pull-left'>
      <img src='/assets/coDogPaw_beige.jpg' class='img-responsive' alt='CO Dog Paw'>
    </span>
  </div>
  <div class='col-xs-10'>
    <span class='footer-blurb'>
      <h1>Recommendations and Warnings for your Colorado Canine</h1>
      <p>The Firehose Project Web App NOMSTER - <a href='http://thefirehoseproject.com'>thefirehoseproject.com</a></p>
    </span>
  </div>
  <div class='col-xs-1'>
    <span class='dog-paw pull-right'>
      <img src = '/assets/coDogPaw_beige.jpg' class='img-responsive' alt='CO Dog Paw'>
    </span>
  </div>
</div>   <!-- container -->
</footer>

</body>
</html>

app/views/places/edit.html.erb
<div class='booyah-box col-xs-10 col-xs-offset-1'>
  <h1>Edit Your Place</h1>
    <%= simple_form_for @place do |f| %>
       <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :description %>
      <br />
      <%= f.submit 'Update', class: 'btn btn-primary' %>
    <% end %>
</div>

app/views/places/index.html.erb
<div id='nomster-carousel-wrapper' class='container-fluid'>
  <div id='nomster-carousel' class='carousel slide' data-ridr='carousel'>

    <!-- Indicators -->
    <ol class='carousel-indicators'>
      <li data-target='#nomster-carousel' data-slide-to='0' class='active'></li>
      <li data-target='#nomster-carousel' data-slide-to='1'></li>
      <li data-target='#nomster-carousel' data-slide-to='2'></li>
      <li data-target='#nomster-carousel' data-slide-to='3'></li>
      <li data-target='#nomster-carousel' data-slide-to='4'></li>
      <li data-target='#nomster-carousel' data-slide-to='5'></li>
      <li data-target='#nomster-carousel' data-slide-to='6'></li>
      <li data-target='#nomster-carousel' data-slide-to='7'></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class='carousel-inner'>
      <div class='item active'>
        <div class='col-xs-12 col-sm-6 col-md-4'><a href='#'>
          <img src='/assets/dogsChairlift_modified.jpg' alt='Chairlift Dogs' class='img-responsive'>
          <div class='carousel-caption'>We came up the easy way</div>
        </a></div>
      </div>
      <div class='item'>
        <div class='col-xs-12 col-sm-6 col-md-4'><a href='#'>
          <img src='/assets/CoSpringsDogParks_modified.jpg' alt='CoS Dog Parks' class='img-responsive'>
        </a></div>        
      </div>
      <div class='item'>
        <div class='col-xs-12 col-sm-6 col-md-4'><a href='#'>
          <img src='/assets/dogPlayGroup_modified.jpg' alt='Playing near Mountains' class='img-responsive'>
          <div class='carousel-caption'>Playing at the base of the Rockies</div>
        </a></div>      
      </div>
      <div class='item'>
        <div class='col-xs-12 col-sm-6 col-md-4'><a href='#'>
          <img src='/assets/aspen_avalanche_modified.jpg' alt='Avalanche Rescue' class='img-responsive'>
          <div class='carousel-caption'>Aspen Avalanche Rescue Dog</div>
        </a></div>
      </div>      
      <div class='item'>
        <div class='col-xs-12 col-sm-6 col-md-4'><a href='#'>
          <img src='/assets/coloradoLabs_modified.jpg' alt='Labs in Colorado' class='img-responsive'>
          <div class='carousel-caption'>Summer Mountain Hike</div>
        </a></div>
      </div>
      <div class='item'>
        <div class='col-xs-12 col-sm-6 col-md-4'><a href='#'>
         <img src='/assets/brewDogsCo_modified.jpg' alt='Brew Dogs' class='img-responsive'>          
        </a></div>
      </div>
      <div class='item'>
        <div class='col-xs-12 col-sm-6 col-md-4'><a href='#'>
          <img src='/assets/coloradoTrail_modified.jpg' alt='Hiking the CO Trail' class='img-responsive'>
          <div class='carousel-caption'>Bernese Mountain Dogs on the Colorado Trail</div>
        </a></div>
      </div>
      <div class='item'>
        <div class='col-xs-12 col-sm-6 col-md-4'><a href='#'>
          <img src='/assets/goldenFourteen_modified.jpg' alt='Golden at 14K ft' class='img-responsive'>
          <div class='carousel-caption'>Top of Colorado: 14,000 Ft</div>
        </a></div>
      </div>      
    </div>   <!-- carousel-inner -->

    <!-- Controls -->
    <a class='left carousel-control' href='#nomster-carousel' data-slide='prev'>
      <span class='glyphicon glyphicon-chevron-left'  aria-hidden='true'></span>
      <span class='sr-only'>Previous</span>
   </a>
    <a class='right carousel-control' href='#nomster-carousel' data-slide='next'>
      <span class='glyphicon glyphicon-chevron-right'  aria-hidden='true'></span>
      <span class='sr-only'>Next</span>
    </a>

  </div>   <!-- id: nomster-carousel -->
</div>   <!-- id: nomster-carousel wrapper -->

<% @places.each do |place| %>
  <div class='booyah-box col-xs-10 col-xs-offset-1'>
    <div class='place-info col-xs-12'>
      <div class='col-xs-12 col-sm-6'>
        <h1><%= link_to place.name, place_path(place) %></h1>
      </div>
      <div class='col-xs-6'>
        <span class='pull-right'>
          <i><%= place.address %></i>
        </span>
      </div>
      <div class='col-xs-12'>
        <p><%= place.description %></p>
        <% if place.user.present? %>
            <small><%= place.user.email %></small>
        <% end %>
      </div>
    </div>

    <!-- last_photo and last_comment defined in place.rb -->
    <div class='place-photo-comment col-xs-12'>
      <% if place.photos.present? %>
        <div class='col-xs-6 col-sm-4 col-md-4'>
          <img src='<%= place.last_photo.picture %>' class='img-responsive' alt='Last Place Photo' style='max-width: 100%'>
        </div>
        <% if place.comments.present? %>
          <div class='col-xs-12 col-sm-8 col-md-8'>
            <blockquote>
              <% if place.last_comment.humanized_rating.present? %>
                <b><%= place.last_comment.humanized_rating %></b>
              <% end %>
              <%= place.last_comment.message %>
              <small><%= place.last_comment.user.email %></small>
            </blockquote>
          </div>
        <% end %>
      <% else %>
        <% if place.comments.present? %>
          <div class='col-xs-12'>
            <blockquote>
             <% if place.last_comment.humanized_rating.present? %>
                <b><%= place.last_comment.humanized_rating %></b>
              <% end %>
              <%= place.last_comment.message %>
              <small><%= place.last_comment.user.email %></small>
            </blockquote>
        </div>
        <% end %>
      <% end %>
    </div>   <!-- end class place-photo-comment -->
  </div>
<% end %>

<div class='digg_pagination'>
  <%= will_paginate @places %>
</div>

<!-- Carousel Slider --- -->
<!-- Code Source
   Bootstrap 3 Show Many Slide One Carousel
   https://github.com/rtpHarry/Bootstrap3-ShowManySlideOneCarousel/wiki/Change-the-number-of-slides-visible-at-any-one-time
-->
<script type='text/javascript'>
  $('#nomster-carousel').carousel( {interval: 4000} );

  $('.carousel .item').each(function(){
    var itemToClone = $(this);

    for (var i=1;i<3;i++) {
      itemToClone = itemToClone.next();

      // wrap around if at end of item collection
      if (!itemToClone.length) {
        itemToClone = $(this).siblings(':first');
      }

      // grab item, clone, add marker class, add to collection
      itemToClone.children(':first-child').clone()
        .addClass("cloneditem-"+(i))
        .appendTo($(this));
    }
  });
</script>





app/views/places/new.html.erb
<div class='booyah-box col-xs-10 col-xs-offset-1'>
  <h1>Enter Your Place Details</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/places/show.html.erb
<div class='booyah-box col-xs-10 col-xs-offset-1'>
  <h1><%= @place.name %></h1>
  <i><%= @place.address %></i>
  <br /><br />
  <p><%= @place.description %></p>
  <br/>

  <div class = 'map-container col-xs-12'>
    <% if @place.latitude.present? && @place.longitude.present? %>
      <script>
        function initMap() {
          var myLatLng = { lat: <%= @place.latitude %>, lng: <%= @place.longitude %> };

          var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 12,
            center: myLatLng
        });

          var marker = new google.maps.Marker({
            position: myLatLng,
            map: map,
            title: 'Hello World!'
          });
        }
      </script>
      <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBN5t_d7HgD6cQ0332SDtKFLCrd6NcFVX8 &callback=initMap">
      </script>
      <div id='map'></div>
    <% end %>
  </div>   <!-- end div map-container' -->
  <div class='clear'></div>

<!-- Source: BlackrockDigital/startbootstrap-thumbnail-gallery -->
  <div class='photo-container col-xs-12'>
      <% @place.photos.each do |photo| %>
        <div class='col-sm-6 col-md-4'>
          <a class='thumbnail' href='#'>
            <img src='<%= photo.picture %>' class='img-responsive' alt='Responsive image'
                      style="width:260px">
          </a>
          <div class='photo-label'>
            <%= photo.caption %>
          </div>
        </div>
      <% end %>
  </div>   <!-- photo-container -->
  <div class='clear'></div>


  <br />
  <div class='pull-right'>
    <% if current_user && current_user == @place.user %>
      <%= link_to 'Edit', edit_place_path(@place), class: 'btn btn-primary' %>
      <button class="btn btn-primary" data-toggle="modal" data-target="#myModalPhotos">
        Add Photos
      </button>
      <%= link_to 'Destroy', place_path(@place), method: :delete,
                                                 data: {confirm: 'Are you sure you want to delete this place?'},
                                                 class: 'btn btn-primary' %>
    <% end %>
  </div>
  <div class='clear'></div>
</div>  <!-- end of div with name, address, description, map and buttons -->

<div class='booyah-box col-xs-10 col-xs-offset-1'>
  <div>
    <h1 class='pull-left'>Comments</h1>
    <!-- Button trigger modal -->
    <button class="btn btn-primary btn-lg pull-right" data-toggle="modal" data-target="#myModalComments">
     Add Your Comment
    </button>
  </div>
  <div class='clear'></div>

  <% @place.comments.each_with_index do |comment, comment_index| %>
    <% if comment_index % 2 == 0 %>
      <div class='clear'></div>
    <% end %>
    <div class='col-xs-12 col-sm-6'>
      <blockquote>
        <% if comment.humanized_rating.present? %>
          <b><%= comment.humanized_rating %></b> -- 
        <% end %>
        <%= comment.message %>
        <small><%= comment.user.email %></small>
      </blockquote>
    </div>
  <% end %>

</div>   <!-- booyah-box for comments -->

<!-- Comments Modal -->
<div class="modal fade" id="myModalComments" tabindex="-1" role="dialog" aria-labelledby="myModalComments" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalComments">Add a Comment</h4>
      </div>
      <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
        <div class="modal-body">
          <%= f.input :message %>
          <%= f.input :rating, as: :select, collection: Comment::RATINGS %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit 'Add Comment', class: 'btn btn-primary' %>
        </div>
       <% end %>
    </div>
  </div>
</div>

<!-- Photos Modal -->
<div class="modal fade" id="myModalPhotos" tabindex="-1" role="dialog" aria-labelledby="myModalPhotos" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalPhotos">Add Photo</h4>
      </div>
      <%= simple_form_for @photo, url: place_photos_path(@place) do |f| %>
        <div class="modal-body">
          <%= f.input :picture %>
          <%= f.input :caption %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close Photo Modal</button>
          <%= f.submit 'Add The Photo', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<!-- end of Photos Model -->





app/views/users/show.html.erb
<div class='booyah-box col-xs-8 col-xs-offset-2 profile-box'>
  <div class='profile-picture col-md-6'>
    <img src='/assets/profilePicture.jpg' class='profile-image img-responsive'>
    <h1><%= @user.email %></h1>
  </div>
  <div class='profile-metrics col-md-4'>    
    <h3>Member Since: <%= @user.created_at.strftime("%B  %Y") %></h3>
    <hr />
    <h4> <%=@user.places.count %> Total Places</h4><br />
    <h4> <%=@user.comments.count %> Total Reviews</h4> <br />
    <h4> <%=@user.comments.where(rating: '5_star').count %> Five-Star Reviews</h4>
  </div>
  <div class='clear'></div>
</div>


<div class='booyah-box col-xs-12'>
  <div class='profile-heading'>
    <h1>My Comments</h1>
  </div>
  <% @comments_sorted = @user.comments.order('rating DESC') %>
  <% @comments_sorted.each_with_index do |comment, comment_index| %>
    <% if comment_index % 2 == 0 %>
      <div class='clear'></div>
    <% end %>
    <div class='item-heading col-xs-12 col-sm-6'>
      <h2><%= link_to comment.place.name, place_path(comment.place) %></h2>
      <blockquote>
        <% if comment.humanized_rating.present? %>
         <b><%= comment.humanized_rating %></b> -- 
       <% end %>
       <%= comment.message %>
      </blockquote>
    </div>
  <% end %>
</div>
<div class='clear'></div>

<div class='booyah-box col-xs-12'>
  <div class='profile-heading'>
    <h1>My Places</h1>
  </div>
  <% @places_sorted = @user.places.order('name ASC') %>
  <% @places_sorted.each_with_index do |place, place_index| %>
    <% if place_index % 2 == 0 %>
      <div class='clear'></div>
    <% end %>
    <div class='item-heading col-xs-12 col-sm-6'>
      <h2><%= link_to place.name, place_path(place) %></h2>
      <i><%= place.address %></i>
      <p><%= place.description%> </p>
    </div>
  <% end %>
</div>
